#!/bin/bash

set -o pipefail

pushd ..
onyx pkg sync
popd

onyx build ../build -o onyx-lsp.wasm

sudo cp ./onyx-lsp /usr/bin/onyx-lsp

sudo mkdir -p /usr/share/onyx/tools
sudo cp ./onyx-lsp.wasm /usr/share/onyx/tools/onyx-lsp.wasm

